version: '3'
services:
    adminer:
        ports:
            - 8080:8080
    node:
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: Dockerfile.prod
        