version: '3'
services:
    adminer:
        ports:
            - 8081:8080
    node:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
        ports:
            - 3001:3000
    webpack:
        build:
          context: .
          dockerfile: Dockerfile.webpack
        volumes:
          - .:/usr/src/app